# Generated by Django 4.1.7 on 2023-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_item_picutre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='picture',
            field=models.ImageField(default='api/media/default.jpg', upload_to='./media/carousel_images'),
        ),
    ]
