# Generated by Django 4.1.7 on 2023-04-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_carousel_picture_alter_item_picutre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='carousel_images'),
        ),
    ]
