# Generated by Django 4.1.7 on 2023-04-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_carousel_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('working_hours', models.JSONField()),
                ('contact_number', models.TextField()),
                ('iframe', models.JSONField()),
            ],
        ),
    ]
