# Generated by Django 4.1.7 on 2023-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_veterinarians_opened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='active',
            new_name='is_link',
        ),
        migrations.AddField(
            model_name='carousel',
            name='link_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='position',
            field=models.TextField(choices=[('1', '2'), ('2', '2'), ('3', '3'), ('4', '4'), ('not_set', 'not_set')], default=1),
            preserve_default=False,
        ),
    ]
