# Generated by Django 4.1.7 on 2023-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_active_carousel_is_link_carousel_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='position',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('not_set', 'not_set')]),
        ),
    ]
