# Generated by Django 4.1.7 on 2023-05-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_carousel_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='duration',
        ),
    ]
