# Generated by Django 4.1.7 on 2023-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_item_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='starting',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
