# Generated by Django 4.1.7 on 2023-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auction_starting_alter_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='ending',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting',
            field=models.DateTimeField(),
        ),
    ]
