# Generated by Django 4.1.7 on 2023-05-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_price_item_minimum_bid_item_starting_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='picutre',
            new_name='picture',
        ),
    ]
