# Generated by Django 4.1.7 on 2023-05-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_picutre_item_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.auction'),
        ),
    ]
