# Generated by Django 4.1.7 on 2023-06-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_auction_item_item_auction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veterinarians',
            new_name='Veterinarian',
        ),
        migrations.AlterField(
            model_name='item',
            name='minimum_bid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.IntegerField(blank=True),
        ),
    ]
