# Generated by Django 4.1.7 on 2023-06-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_cat_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='cat_images/'),
        ),
    ]
