# Generated by Django 4.1.7 on 2023-06-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_cat_info_alter_cat_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='status',
            field=models.TextField(choices=[('pending', 'pending'), ('read', 'read')], default='pending'),
        ),
    ]
