# Generated by Django 4.1.7 on 2023-06-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_donations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
    ]
