# Generated by Django 4.2.3 on 2023-07-28 11:35

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.DateField(default=date.today),
        ),
    ]
