# Generated by Django 4.2.3 on 2023-07-28 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
