# Generated by Django 4.0.4 on 2023-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='minimum_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
